yongilkim01/UE_Overcooked2

- Overcooked2/Source/Overcooked2/LevelContent/Table/CookingTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/PrepTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/PrepTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/SpawnTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/SpawnTable.h
> 이수환: CookingTable 함수 변경

- Overcooked2/Source/Overcooked2/LevelContent/Table/CookingTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/SpawnTable.cpp
> 이수환: 함수 수정

- Overcooked2/Source/Overcooked2/UI/Cooking/UI/CookingWidget.cpp
> 강민정 : 주문 UI 이미지 크기에 따른 위치 변경

- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/PrepTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/PrepTable.h
> 이수환 : 기본 함수 추가

- Overcooked2/Source/Overcooked2/LevelContent/WorldMap/TileGrid.cpp
> 전혜주 : 빌드 안되는 문제 수정

- Overcooked2/Source/Overcooked2/LevelContent/Table/CookingTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/SpawnTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/SpawnTable.h
이수환 : SpawnTable 상호작용 함수, Prep 준비
> 이수환 : SpawnTable 상호작용 함수, Prep 준비

- Overcooked2/Source/Overcooked2/LevelContent/Table/SpawnTable.cpp
> 이수환 : 에러 해결

- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/PrepTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/PrepTable.h
> 이수환 : ChoppingTable 만들기

- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.cpp
> 이수환 : 오류 수정

- Overcooked2/Source/Overcooked2/Character/OC2Character.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/BurnerTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/BurnerTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/CookingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/CookingTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/GarbageCan.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/GarbageCan.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/PrepTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/PrepTable.h
이수환 : Table 하위 클래스 함수 수정 + OC2Character ChopIngredient()
> 이수환 : Table 하위 클래스 함수 수정 + OC2Character ChopIngredient()

- Overcooked2/Source/Overcooked2/LevelContent/Table/BurnerTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/CookingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/PlateSpawner.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/PlateSpawner.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/ServingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/ServingTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/SinkTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/SinkTable.h
이수환 : ChoppingTable 다지기 구현, NonTable 함수 추가
> 이수환 : ChoppingTable 다지기 구현, NonTable 함수 추가

- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.h
> 이수환 : ChoppingIsDone() 수정

- Overcooked2/Source/Overcooked2/LevelContent/Table/BurnerTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.cpp
이수환 : ChoppingTable 함수 수정, BurnerTable CookingPtr 조건문 수정
> 이수환 : ChoppingTable 함수 수정, BurnerTable CookingPtr 조건문 수정

- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/PlateSpawner.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/PlateSpawner.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/SinkTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/SinkTable.h
> 이수환 : PlateSpawner 함수 추가중 

- Overcooked2/Source/Overcooked2/UI/Cooking/UI/CookingWidget.cpp
- Overcooked2/Source/Overcooked2/UI/Cooking/UI/CookingWidget.h
> 강민정 : 쿠킹 타이머 위젯 수정

- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/CookingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/CookingTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/SinkTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/SinkTable.h
이수환 : Chopping Table, Sink Table 동기화
> 이수환 : Chopping Table, Sink Table 동기화

- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/SinkTable.cpp
이수환 : SinkTable DirtyPlate visible 설정 동기화 확인중
> 이수환 : SinkTable DirtyPlate visible 설정 동기화 확인중

- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/SinkTable.cpp
이수환 : SinkTable ProgressBar 위치 수정
> 이수환 : SinkTable ProgressBar 위치 수정

- Overcooked2/Source/Overcooked2/LevelContent/Table/BurnerTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/BurnerTable.h
- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.h
이수환 : Chopping Table warning 해결
> 이수환 : Chopping Table warning 해결

- Overcooked2/Source/Overcooked2/LevelContent/Cook/Plate.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/SinkTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/SinkTable.h
> 이수환 : SinkTable 수정

- Overcooked2/Source/Overcooked2/Global/GameMode/CookingGameMode.cpp
- Overcooked2/Source/Overcooked2/Global/OC2GameInstance.cpp
- Overcooked2/Source/Overcooked2/Global/OC2GameInstance.h
- Overcooked2/Source/Overcooked2/Global/State/GameState/WorldGameState.cpp
- Overcooked2/Source/Overcooked2/LevelContent/WorldMap/WorldGameMode.cpp
- Overcooked2/Source/Overcooked2/Lobby/LobbyGameMode.cpp
- Overcooked2/Source/Overcooked2/Lobby/LobbyPlayerController.cpp
> 강민정 : 패키징 오류 해결

- Overcooked2/Source/Overcooked2/LevelContent/Table/CookingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/CookingTable.h
> 이수환 : CookingTable 사운드 동기화

- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/SinkTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/NonTable/SinkTable.h
> 이수환 : SinkTable 사운드 동기화

- Overcooked2/Source/Overcooked2/UI/Cooking/UI/CookingFinalScoreWidget.cpp
- Overcooked2/Source/Overcooked2/UI/Cooking/UI/CookingFinalScoreWidget.h
- Overcooked2/Source/Overcooked2/UI/Cooking/UI/CookingWidget.cpp
> 강민정 : 쿠킹 최종 스코어 TextureUI 수정 중

- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/CookingTable.cpp
> 이수환 : cucumber 회전

- Overcooked2/Source/Overcooked2/LevelContent/Table/ChoppingTable.cpp
- Overcooked2/Source/Overcooked2/LevelContent/Table/CookingTable.cpp
> 이수환 : Prawn 위치 조정

- Overcooked2/Source/Overcooked2/UI/Cooking/UI/CookingWidget.cpp
- Overcooked2/Source/Overcooked2/UI/Cooking/UI/CookingWidget.h
> 강민정 : 쿠킹 오더 UI 수정

- Overcooked2/Source/Overcooked2/Global/GameMode/CookingGameMode.h
- Overcooked2/Source/Overcooked2/Global/OC2Global.cpp
- Overcooked2/Source/Overcooked2/Global/OC2Global.h
- Overcooked2/Source/Overcooked2/UI/Cooking/UI/CookingReceiptWidget.cpp
> 강민정 : 오류 수정 커밋

- Overcooked2/Source/Overcooked2/UI/Cooking/UI/CookingWidget.cpp
> 강민정 : 쿠킹 오더 UI 오류 수정 중
